name: fast_json
version: 0.1.10
description: Collection of JSON parsers. Classic parser (also with BigNum support), event-based parser. Pretty quick parsing.
repository: https://github.com/mezoni/fast_json
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
dev_dependencies:
  lints: '<3.0.0'
  parser_builder: 2.0.25
  test: ^1.20.1
